### ISSUE TITLE
due.sh do not have images

### ISSUE THREAD

**Issue by chizhanyuefeng** [nttmdlab-nlp/InstructDoc#5]
Thanks for this work! 
But when I want to process due data, the png/jpg images was not download.
How can I download these image data

**Comment by rtanaka-lab** [comment]
Thanks for having an interest in our work.

We first downloaded original PDF documents in [official DUE datasets](http://duebenchmark.com/data), and then we used [pdf2image](https://pypi.org/project/pdf2image/) to convert PDF into images. 

The current version of our code is not supported in this process, but we will support it.
