### ISSUE TITLE
can't find file ai2d_test_ids.csv

### ISSUE THREAD

**Issue by G-z-w** [nttmdlab-nlp/InstructDoc#6]
How could I get the ai2d_test_ids.csv file?

**Comment by rtanaka-lab** [comment]
Thank you for the question.
We can get it from [https://s3-us-east-2.amazonaws.com/prior-datasets/ai2d_test_ids.csv](https://s3-us-east-2.amazonaws.com/prior-datasets/ai2d_test_ids.csv).
